In [2]:
## 1. Split this string


In [3]:
s = "Hi there Sam!"

In [4]:
s.split()

['Hi', 'there', 'Sam!']

In [5]:
## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [6]:
planet = "Earth"
diameter = 12742

In [7]:
print("The diameter of {} is {} kilometers".format(planet,diameter))


The diameter of Earth is 12742 kilometers


In [8]:
## 3. In this nest dictionary grab the word "hello"

In [9]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [10]:
d['k1'][3]['tricky'][3]['target'][3]

'hello'

In [11]:
# Numpy

In [12]:
import numpy as np

In [13]:
## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [14]:
array=np.zeros(10)
print(array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [15]:
array=np.ones(10)*5
print(array)


[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [16]:
## 5. Create an array of all the even integers from 20 to 35

In [17]:
array=np.arange(20,35,2)
print(array)

[20 22 24 26 28 30 32 34]


In [18]:
## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [19]:
x=np.arange(0,9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [20]:
## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [21]:
 a = np.array([1,2,3])
 b = np.array([4,5,6])
 x=np.concatenate((a,b))
 print(x)

[1 2 3 4 5 6]


In [22]:
# Pandas

In [23]:
## 8. Create a dataframe with 3 rows and 2 columns

In [24]:
import pandas as pd
data= [['tom',10],['nick',12],['john',13]]
df = pd.DataFrame(data,columns=['name','age'])
df


name  age
0   tom   10
1  nick   12
2  john   13

In [25]:
## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [26]:
x = pd.date_range(start = '1-1-2023',end = '10-2-2023',freq = 'D')
for val in x:
  print(x)

DatetimeIndex(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04',
               '2023-01-05', '2023-01-06', '2023-01-07', '2023-01-08',
               '2023-01-09', '2023-01-10',
               ...
               '2023-09-23', '2023-09-24', '2023-09-25', '2023-09-26',
               '2023-09-27', '2023-09-28', '2023-09-29', '2023-09-30',
               '2023-10-01', '2023-10-02'],
              dtype='datetime64[ns]', length=275, freq='D')
DatetimeIndex(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04',
               '2023-01-05', '2023-01-06', '2023-01-07', '2023-01-08',
               '2023-01-09', '2023-01-10',
               ...
               '2023-09-23', '2023-09-24', '2023-09-25', '2023-09-26',
               '2023-09-27', '2023-09-28', '2023-09-29', '2023-09-30',
               '2023-10-01', '2023-10-02'],
              dtype='datetime64[ns]', length=275, freq='D')
DatetimeIndex(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04',
               '2023-01-05', 

In [27]:
## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [28]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [29]:
df = pd.DataFrame(lists)
df

0    1   2
0  1  aaa  22
1  2  bbb  25
2  3  ccc  24